import { createElement } from 'lwc';
import NV_lwc_newFlight from 'c/nV_lwc_newFlight';

describe('c-n-v-lwc-new-flight', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-n-v-lwc-new-flight', {
            is: NV_lwc_newFlight
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});